version: '3.8'
services:
  grobid:
    image: lfoppiano/grobid:0.7.3
    ports:
      - "8070:8070"
    volumes:
      - ./grobid-home:/opt/grobid/grobid-home
    environment:
      - JAVA_OPTS=-Xmx4g